# Generated by Django 6.1.1 on 2026-09-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cron job name', max_length=255, unique=True, verbose_name='Name')),
                ('func_path', models.CharField(help_text='Callable function path', max_length=500, verbose_name='Function path')),
                ('cron_expression', models.CharField(help_text='Cron expression or preset', max_length=100, verbose_name='Cron expression')),
                ('active', models.BooleanField(default=True, help_text='Is cron job active', verbose_name='Active')),
                ('last_run', models.DateField(blank=True, help_text='Last execution date', null=True, verbose_name='Last run date')),
                ('last_run_time', models.TimeField(blank=True, help_text='Last execution time', null=True, verbose_name='Last run time')),
                ('next_run', models.DateField(blank=True, help_text='Next execution date', null=True, verbose_name='Next run date')),
                ('next_run_time', models.TimeField(blank=True, help_text='Next execution time', null=True, verbose_name='Next run time')),
                ('trashed', models.BooleanField(default=False, help_text='Marked as deleted', verbose_name='Trashed')),
            ],
            options={
                'verbose_name': 'Scheduled job',
                'verbose_name_plural': 'Scheduled jobs',
            },
        ),
        migrations.CreateModel(
            name='HookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_name', models.CharField(help_text='Hook identifier', max_length=255, verbose_name='Hook name')),
                ('callback_name', models.CharField(help_text='Executed callback function', max_length=255, verbose_name='Callback name')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='Execution start time', verbose_name='Start time')),
                ('end_time', models.DateTimeField(blank=True, help_text='Execution end time', null=True, verbose_name='End time')),
                ('execution_time_ms', models.FloatField(blank=True, help_text='Execution duration in milliseconds', null=True, verbose_name='Execution time (ms)')),
                ('status', models.CharField(default='success', help_text='Execution status', max_length=50, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed', null=True, verbose_name='Error message')),
                ('trashed', models.BooleanField(default=False, help_text='Marked as deleted', verbose_name='Trashed')),
            ],
            options={
                'verbose_name': 'Hook log',
                'verbose_name_plural': 'Hook logs',
            },
        ),
    ]
