"""
constants.py - ثابت‌های پروژه
"""

# تنظیمات Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# محدودیت‌ها
MAX_FIELDS_PER_REQUEST = 50
DEFAULT_RATE_LIMIT_MAX_REQUESTS = 50
DEFAULT_RATE_LIMIT_WINDOW_SECONDS = 10
# کدهای خطا
ERROR_CODES = {
    'INVALID_INPUT': 'INVALID_INPUT',
    'VALIDATION_ERROR': 'VALIDATION_ERROR',
    'UNAUTHENTICATED': 'UNAUTHENTICATED',
    'PERMISSION_DENIED': 'PERMISSION_DENIED',
    'MODEL_NOT_FOUND': 'MODEL_NOT_FOUND',
    'OBJECT_NOT_FOUND': 'OBJECT_NOT_FOUND',
    'METHOD_NOT_ALLOWED': 'METHOD_NOT_ALLOWED',
    'METHOD_NOT_CALLABLE': 'METHOD_NOT_CALLABLE',
    'INTERNAL_ERROR': 'INTERNAL_ERROR',
    'RATE_LIMITED': 'RATE_LIMITED',
}
